ARG BASE_TAG="1.17.0"
ARG BASE_IMAGE="core-ubuntu-jammy:"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS_DIR $STARTUPDIR/install
WORKDIR $HOME

### Envrionment config
ENV DEBUG=false \
    DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="/ubuntu/install/dind_rootless/install_dind_rootless_prerequisites.sh \
                  /ubuntu/install/dind_rootless/install_dind_rootless.sh \
                  /ubuntu/install/tools/install_tools_deluxe.sh \
                  /ubuntu/install/misc/install_tools.sh \
                  /ubuntu/install/chromium/install_chromium.sh \
                  /ubuntu/install/vs_code/install_vs_code.sh \
                  /ubuntu/install/cleanup/cleanup.sh"

# Startup Scripts
COPY ./src/ubuntu/install/dind_rootless/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh
COPY ./src/ubuntu/install/dind/dockerd.conf /etc/supervisor/conf.d/

# Copy install scripts
COPY ./src/ $INST_DIR
USER 1000
# Run installations
RUN \
  for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT} || exit 1; \
  done
######### Customize Container Here ###########
USER root
# Maltego wants a browser installed and the default is Firefox, Install Firefox
COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS_DIR/firefox/
COPY ./src/ubuntu/install/firefox/firefox.desktop $HOME/Desktop/
RUN bash $INST_SCRIPTS_DIR/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS_DIR/firefox/

# Install Maltego
COPY ./src/ubuntu/install/maltego $INST_SCRIPTS_DIR/maltego/
RUN bash $INST_SCRIPTS_DIR/maltego/install_maltego.sh  && rm -rf $INST_SCRIPTS_DIR/maltego/

######### End Customizations ###########
RUN \  
  $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/kasm-user && \
  chown -R 1000:0 /home/kasm-user && \
  rm -Rf ${INST_DIR}

# Userspace Runtime
ENV HOME /home/kasm-user
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]
